// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNQYjTnP8tItja-qtbwaG01E4R3wzL_-4',
    appId: '1:295400968333:web:542dfeabdcfe5a0b6412c4',
    messagingSenderId: '295400968333',
    projectId: 'aiwrapper-96714',
    authDomain: 'aiwrapper-96714.firebaseapp.com',
    storageBucket: 'aiwrapper-96714.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACBqH4IeB7zoe6u2svM7X8uFnyeMNyCr4',
    appId: '1:295400968333:android:68f4cf6112d558e96412c4',
    messagingSenderId: '295400968333',
    projectId: 'aiwrapper-96714',
    storageBucket: 'aiwrapper-96714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfL92TeFqqn6tvUsD_f_gim8ZBqCFLBiQ',
    appId: '1:295400968333:ios:52f2cd5495a0947c6412c4',
    messagingSenderId: '295400968333',
    projectId: 'aiwrapper-96714',
    storageBucket: 'aiwrapper-96714.firebasestorage.app',
    iosBundleId: 'com.example.aiWrapperApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfL92TeFqqn6tvUsD_f_gim8ZBqCFLBiQ',
    appId: '1:295400968333:ios:52f2cd5495a0947c6412c4',
    messagingSenderId: '295400968333',
    projectId: 'aiwrapper-96714',
    storageBucket: 'aiwrapper-96714.firebasestorage.app',
    iosBundleId: 'com.example.aiWrapperApp',
  );
}
